// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Prodigy75000

//! iNES header-correction database.
//!
//! Old dump sets (the euroemu/GoodNES-era `.nes` files a lot of libraries are
//! built from) frequently carry the WRONG mapper number in the iNES header —
//! e.g. dozens of UNROM (mapper 2) games tagged as GxROM (mapper 66). The header
//! is just metadata bolted onto the ROM by the dumper; the silicon is whatever it
//! is. Emulators that boot these games (Nestopia, Mesen) do it by overriding the
//! header from an internal database keyed on the ROM's checksum. We do the same.
//!
//! We key on the CRC32 of the ROM DATA — everything after the 16-byte iNES header
//! (trainer + PRG + CHR) — so the fix is header-independent: a re-headered copy of
//! the same cart still matches. Entries are produced by the `gen_header_db` dev
//! bin, which boot-verifies each correction against this very core (it renders
//! under the corrected mapper and not under the header's), so the table is our own
//! empirical measurement, not a copy of anyone else's database.

/// CRC32 (IEEE 802.3, polynomial 0xEDB88320) of the cart data: the bytes after
/// the 16-byte iNES header. Bit-serial — run once at load, ROM-sized, negligible.
pub fn rom_data_crc32(rom: &[u8]) -> u32 {
    let data = if rom.len() > 16 { &rom[16..] } else { &[][..] };
    let mut crc = 0xffff_ffffu32;
    for &b in data {
        crc ^= b as u32;
        for _ in 0..8 {
            let mask = (crc & 1).wrapping_neg();
            crc = (crc >> 1) ^ (0xedb8_8320 & mask);
        }
    }
    !crc
}

use crate::cart::Mirroring;

/// A per-cart header override. Every field is applied only when `Some`; `None`
/// leaves the header's own value untouched. This is the whole cart configuration
/// the iNES header can get wrong — not just the mapper but mirroring, the RAM
/// sizes, and the battery flag — so the DB can correct all of it by checksum.
/// (Submapper is intentionally absent until a mapper actually differentiates on
/// it; there's no point storing data nothing reads.)
#[derive(Clone, Copy)]
pub struct HeaderFix {
    pub mapper: Option<u16>,
    pub mirroring: Option<Mirroring>,
    pub prg_ram: Option<usize>,
    pub chr_ram: Option<usize>,
    pub battery: Option<bool>,
}

impl HeaderFix {
    const EMPTY: HeaderFix = HeaderFix {
        mapper: None,
        mirroring: None,
        prg_ram: None,
        chr_ram: None,
        battery: None,
    };
    /// The common case: correct only the mapper number.
    const fn mapper(m: u16) -> HeaderFix {
        HeaderFix { mapper: Some(m), ..HeaderFix::EMPTY }
    }
}

/// The header correction for a cart whose iNES header is known-wrong, or `None`
/// to trust the header. Looked up by [`rom_data_crc32`].
pub fn correction(data_crc: u32) -> Option<&'static HeaderFix> {
    HEADER_FIXES
        .binary_search_by_key(&data_crc, |&(crc, _)| crc)
        .ok()
        .map(|i| &HEADER_FIXES[i].1)
}

/// `(rom-data CRC32, HeaderFix)`, sorted by CRC for binary search. The mapper
/// entries are GENERATED by the `gen_header_db` bin (boot-verified); richer
/// fixes (mirroring / RAM / battery) are hand-added as evidence surfaces.
static HEADER_FIXES: &[(u32, HeaderFix)] = &[
    // UNROM (mapper 2) games mislabeled GxROM (66) by the euroemu/GoodNES set.
    // Generated by `gen_header_db` from the licensed corpus (boot-verified: each
    // renders as UNROM and stays black under mapper 66). Sorted by CRC.
    (0x1d0f4d6b, HeaderFix::mapper(2)), // Black Bass USA, The (U).nes
    // CNROM (mapper 3) carts wearing a "DiskDude!" header: byte 7 is the string's
    // 'D' (0x44) and byte 6's nibble is 0, so BOTH nibbles are wrong -- the archaic
    // heuristic can't recover these (it would give mapper 0/NROM, whose dead CHR
    // banking garbles banked graphics). Boot-verified as CNROM (32 KiB PRG fixed +
    // 32 KiB CHR banked): CNROM renders Gyruss' solar-system + intro clean, whereas
    // RAMBO-1 (which the naive header suggests) garbles the borders. NOTE: Gyruss'
    // in-game score/stage HUD is still missing under CNROM -- a separate rendering
    // bug (not a mapper mismatch), left for a gameplay-focused pass.
    (0x1d41cc8c, HeaderFix::mapper(3)),  // Gyruss (U).nes
    (0x1d5b03a5, HeaderFix::mapper(2)),  // Jackal (U).nes
    (0x35b6febf, HeaderFix::mapper(2)), // NFL Football (U).nes
    (0x3be244ef, HeaderFix::mapper(2)), // Little Mermaid, The (U).nes
    (0x3efa7e44, HeaderFix::mapper(2)), // Mega Girl (Hack).nes
    (0x423ada8e, HeaderFix::mapper(2)), // Skate or Die! (U).nes
    (0x55773880, HeaderFix::mapper(2)), // Gilligan's Island (U).nes
    (0x6ee4bb0a, HeaderFix::mapper(2)), // Mega Man (U).nes
    (0x703e1948, HeaderFix::mapper(3)), // Donkey Kong Classics (U).nes -- CNROM (DiskDude header)
    (0x7655d26b, HeaderFix::mapper(2)), // Mega Man in Icarus World (Hack).nes
    (0x848c84ee, HeaderFix::mapper(2)), // ZZZ_UNK_Bomber King (J)a.nes
    (0xa0ddf884, HeaderFix::mapper(2)), // Bomberman 2 (J) [p1][hM02].nes
    (0xa2194cad, HeaderFix::mapper(2)), // Legendary Wings (U).nes
    (0xaa6bb985, HeaderFix::mapper(2)), // Kid Kool (U).nes
    (0xacb01473, HeaderFix::mapper(2)), // Mega Man - Wily's Conquest (Mega Man Hack).nes
    (0xb5d28ea2, HeaderFix::mapper(3)), // Mystery Quest (U).nes -- CNROM (DiskDude header)
    (0xc6000085, HeaderFix::mapper(2)), // Conan (U).nes
    (0xca033b3a, HeaderFix::mapper(2)), // Dragon's Lair (U).nes
    (0xdc4da5d4, HeaderFix::mapper(2)), // Side Pocket (U).nes
    (0xde25b90f, HeaderFix::mapper(2)), // Rush'n Attack (U).nes
    (0xf610ec76, HeaderFix::mapper(2)), // Jackal (U) [T-Port].nes
    (0xfd8d6c75, HeaderFix::mapper(2)), // Loopz (U).nes
    (0xfeade8cb, HeaderFix::mapper(2)), // RockMan Zero by MB Hacks (Hack).nes
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crc32_known_vector() {
        // CRC32 of the ASCII "123456789" is the standard 0xCBF43926. Our function
        // skips the first 16 bytes, so prepend a 16-byte dummy header.
        let mut buf = vec![0u8; 16];
        buf.extend_from_slice(b"123456789");
        assert_eq!(rom_data_crc32(&buf), 0xcbf4_3926);
    }

    #[test]
    fn table_is_sorted_and_searchable() {
        // Binary search requires the table stay sorted by CRC; guard it.
        for w in HEADER_FIXES.windows(2) {
            assert!(w[0].0 < w[1].0, "HEADER_FIXES must be sorted by CRC, ascending");
        }
        for &(crc, fix) in HEADER_FIXES {
            assert_eq!(correction(crc).map(|f| f.mapper), Some(fix.mapper));
        }
        assert!(correction(0x0000_0000).is_none(), "unknown CRC must not match");
    }

    #[test]
    fn richer_fix_carries_all_fields() {
        // The record can express more than the mapper (this is the step-2 point).
        let fix = HeaderFix {
            mapper: Some(1),
            mirroring: Some(Mirroring::Vertical),
            prg_ram: Some(32 * 1024),
            chr_ram: None,
            battery: Some(true),
        };
        assert_eq!(fix.mapper, Some(1));
        assert_eq!(fix.mirroring, Some(Mirroring::Vertical));
        assert_eq!(fix.prg_ram, Some(32 * 1024));
        assert_eq!(fix.battery, Some(true));
        // mapper-only helper leaves the rest untouched.
        let m = HeaderFix::mapper(2);
        assert_eq!(m.mapper, Some(2));
        assert!(m.mirroring.is_none() && m.prg_ram.is_none() && m.battery.is_none());
    }
}
