//! iNES header-correction database.
//!
//! Old dump sets (the euroemu/GoodNES-era `.nes` files a lot of libraries are
//! built from) frequently carry the WRONG mapper number in the iNES header —
//! e.g. dozens of UNROM (mapper 2) games tagged as GxROM (mapper 66). The header
//! is just metadata bolted onto the ROM by the dumper; the silicon is whatever it
//! is. Emulators that boot these games (Nestopia, Mesen) do it by overriding the
//! header from an internal database keyed on the ROM's checksum. We do the same.
//!
//! We key on the CRC32 of the ROM DATA — everything after the 16-byte iNES header
//! (trainer + PRG + CHR) — so the fix is header-independent: a re-headered copy of
//! the same cart still matches. Entries are produced by the `gen_header_db` dev
//! bin, which boot-verifies each correction against this very core (it renders
//! under the corrected mapper and not under the header's), so the table is our own
//! empirical measurement, not a copy of anyone else's database.

/// CRC32 (IEEE 802.3, polynomial 0xEDB88320) of the cart data: the bytes after
/// the 16-byte iNES header. Bit-serial — run once at load, ROM-sized, negligible.
pub fn rom_data_crc32(rom: &[u8]) -> u32 {
    let data = if rom.len() > 16 { &rom[16..] } else { &[][..] };
    let mut crc = 0xffff_ffffu32;
    for &b in data {
        crc ^= b as u32;
        for _ in 0..8 {
            let mask = (crc & 1).wrapping_neg();
            crc = (crc >> 1) ^ (0xedb8_8320 & mask);
        }
    }
    !crc
}

/// The corrected mapper for a cart whose header is known-wrong, or `None` to
/// trust the header. Looked up by [`rom_data_crc32`].
pub fn corrected_mapper(data_crc: u32) -> Option<u16> {
    HEADER_FIXES
        .binary_search_by_key(&data_crc, |&(crc, _)| crc)
        .ok()
        .map(|i| HEADER_FIXES[i].1)
}

/// `(rom-data CRC32, correct mapper)`, sorted by CRC for binary search.
/// GENERATED by the `gen_header_db` bin (boot-verified) — do not hand-edit.
static HEADER_FIXES: &[(u32, u16)] = &[
    // UNROM (mapper 2) games mislabeled GxROM (66) by the euroemu/GoodNES set.
    // Generated by `gen_header_db` from the licensed corpus (boot-verified: each
    // renders as UNROM and stays black under mapper 66). Sorted by CRC.
    (0x1d0f4d6b, 2), // Black Bass USA, The (U).nes
    (0x1d5b03a5, 2), // Jackal (U).nes
    (0x35b6febf, 2), // NFL Football (U).nes
    (0x3be244ef, 2), // Little Mermaid, The (U).nes
    (0x3efa7e44, 2), // Mega Girl (Hack).nes
    (0x423ada8e, 2), // Skate or Die! (U).nes
    (0x55773880, 2), // Gilligan's Island (U).nes
    (0x6ee4bb0a, 2), // Mega Man (U).nes
    (0x7655d26b, 2), // Mega Man in Icarus World (Hack).nes
    (0x848c84ee, 2), // ZZZ_UNK_Bomber King (J)a.nes
    (0xa0ddf884, 2), // Bomberman 2 (J) [p1][hM02].nes
    (0xa2194cad, 2), // Legendary Wings (U).nes
    (0xaa6bb985, 2), // Kid Kool (U).nes
    (0xacb01473, 2), // Mega Man - Wily's Conquest (Mega Man Hack).nes
    (0xc6000085, 2), // Conan (U).nes
    (0xca033b3a, 2), // Dragon's Lair (U).nes
    (0xdc4da5d4, 2), // Side Pocket (U).nes
    (0xde25b90f, 2), // Rush'n Attack (U).nes
    (0xf610ec76, 2), // Jackal (U) [T-Port].nes
    (0xfd8d6c75, 2), // Loopz (U).nes
    (0xfeade8cb, 2), // RockMan Zero by MB Hacks (Hack).nes
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn crc32_known_vector() {
        // CRC32 of the ASCII "123456789" is the standard 0xCBF43926. Our function
        // skips the first 16 bytes, so prepend a 16-byte dummy header.
        let mut buf = vec![0u8; 16];
        buf.extend_from_slice(b"123456789");
        assert_eq!(rom_data_crc32(&buf), 0xcbf4_3926);
    }

    #[test]
    fn table_is_sorted_and_searchable() {
        // Binary search requires the table stay sorted by CRC; guard it.
        for w in HEADER_FIXES.windows(2) {
            assert!(w[0].0 < w[1].0, "HEADER_FIXES must be sorted by CRC, ascending");
        }
        for &(crc, mapper) in HEADER_FIXES {
            assert_eq!(corrected_mapper(crc), Some(mapper));
        }
    }
}
