; SPDX-License-Identifier: CC0-1.0
; NOISY NEIGHBORS -- what the art is called. GENERATED by tools/genart.py.
;
; The code never writes a tile number. It writes a block id and looks the tiles
; up here, so the art and the game cannot disagree about what a thing is.

BLK_AIR        = 0
BLK_STONE      = 1
BLK_PLAT       = 2
BLK_LIAR       = 3
BLK_CRUMBLE    = 4
BLK_RUBBLE     = 5
BLK_SPIKEUP    = 6
BLK_SPIKEDN    = 7
BLK_LAVA       = 8
BLK_TORCH      = 9
BLK_CHAIN      = 10
BLK_BACKBRICK  = 11
BLK_DOOR       = 12
NUM_BLOCKS   = 13

BF_SOLID   = $01
BF_HAZARD  = $02
BF_CRUMBLE = $04
BF_GOAL    = $08

E_NONE     = 0
E_BAIT     = 1
E_SAW      = 2
E_CRUSHER  = 3
E_DARTR    = 4
E_DARTL    = 5
E_COUNT    = 6

MS_HERO_IDLE  = 0
MS_HERO_WALK1 = 1
MS_HERO_WALK2 = 2
MS_HERO_JUMP  = 3
MS_HERO_DEAD  = 4
MS_BANANA     = 5
MS_SAW        = 6
MS_CRUSHER    = 7
MS_COUNT   = 8
SPR_DART   = 28
SPR_SKULL  = 29

blk_tl:  ; background tile in the TL corner of each block
  .byte $00, $40, $42, $42, $44, $48, $4B, $4E
  .byte $51, $54, $58, $5A, $5C

blk_tr:  ; background tile in the TR corner of each block
  .byte $00, $40, $42, $42, $45, $48, $4B, $4F
  .byte $52, $55, $59, $5B, $5D

blk_bl:  ; background tile in the BL corner of each block
  .byte $00, $41, $43, $43, $46, $49, $4C, $50
  .byte $53, $56, $58, $5A, $5E

blk_br:  ; background tile in the BR corner of each block
  .byte $00, $41, $43, $43, $47, $4A, $4D, $50
  .byte $53, $57, $59, $5B, $5F

blk_flags:  ; solid / hazard / crumble / goal
  .byte $00, $01, $01, $00, $05, $00, $02, $02
  .byte $02, $00, $00, $00, $08

blk_pal:  ; which background palette the block wants
  .byte $00, $01, $02, $02, $02, $02, $01, $01
  .byte $03, $03, $01, $01, $02

BLKF_PLAT  = $01
BLKP_PLAT  = 2
BLKF_LIAR  = $00
BLKP_LIAR  = 2
LIAR_TILES_MATCH = 1

charmap:  ; room character (the byte .str emits) -> block id
  .byte $00, $00, $00, $01, $00, $0B, $00, $00
  .byte $00, $00, $09, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $01, $02, $01, $00
  .byte $00, $00, $00, $00, $0C, $00, $00, $00
  .byte $00, $00, $00, $00, $08, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $06, $00
  .byte $00, $00, $00, $04, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $05
  .byte $00, $00, $00, $00, $00, $00, $07, $00
  .byte $00, $00, $00, $00, $0A, $00, $03, $00

charent:  ; room character -> entity spawned in that cell
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $05, $00, $04, $00
  .byte $00, $00, $01, $03, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $02
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00

CH_SPAWN1 = $11  ; where player 1 starts the room
CH_SPAWN2 = $12  ; where player 2 starts the room

ms_tl:  ; sprite tile in the TL corner of each metasprite
  .byte $00, $00, $00, $08, $0C, $10, $14, $18

ms_tr:  ; sprite tile in the TR corner of each metasprite
  .byte $01, $01, $01, $09, $0D, $11, $15, $19

ms_bl:  ; sprite tile in the BL corner of each metasprite
  .byte $02, $04, $06, $0A, $0E, $12, $16, $1A

ms_br:  ; sprite tile in the BR corner of each metasprite
  .byte $03, $05, $07, $0B, $0F, $13, $17, $1B

