; SPDX-License-Identifier: CC0-1.0
; NOISY NEIGHBORS -- what the art is called. GENERATED by tools/genart.py.
;
; The code never writes a tile number. It writes a block id and looks the tiles
; up here, so the art and the game cannot disagree about what a thing is.

BLK_AIR        = 0
BLK_STONE      = 1
BLK_PLAT       = 2
BLK_CLOSET     = 3
BLK_CRUMBLE    = 4
BLK_RUBBLE     = 5
BLK_SPIKEUP    = 6
BLK_SPIKEDN    = 7
BLK_LAVA       = 8
BLK_TORCH      = 9
BLK_CHAIN      = 10
BLK_BACKBRICK  = 11
BLK_DOOR       = 12
NUM_BLOCKS   = 13

BF_SOLID   = $01
BF_HAZARD  = $02
BF_CRUMBLE = $04
BF_GOAL    = $08
BF_HIDE    = $10

MS_HERO_IDLE  = 0
MS_HERO_WALK1 = 1
MS_HERO_WALK2 = 2
MS_HERO_JUMP  = 3
MS_HERO_DEAD  = 4
MS_BANANA     = 5
MS_SAW        = 6
MS_CRUSHER    = 7
MS_COUNT   = 8
SPR_DART   = 28
SPR_SKULL  = 29

blk_tl:  ; background tile in the TL corner of each block
  .byte $00, $40, $42, $44, $48, $4C, $4F, $52
  .byte $55, $58, $5C, $5E, $60

blk_tr:  ; background tile in the TR corner of each block
  .byte $00, $40, $42, $45, $49, $4C, $4F, $53
  .byte $56, $59, $5D, $5F, $61

blk_bl:  ; background tile in the BL corner of each block
  .byte $00, $41, $43, $46, $4A, $4D, $50, $54
  .byte $57, $5A, $5C, $5E, $62

blk_br:  ; background tile in the BR corner of each block
  .byte $00, $41, $43, $47, $4B, $4E, $51, $54
  .byte $57, $5B, $5D, $5F, $63

blk_flags:  ; solid / hazard / crumble / goal
  .byte $00, $01, $01, $10, $05, $00, $02, $02
  .byte $02, $00, $00, $00, $08

blk_pal:  ; which background palette the block wants
  .byte $00, $01, $02, $02, $02, $02, $01, $01
  .byte $03, $03, $01, $01, $02

BLKF_PLAT   = $01
BLKP_PLAT   = 2
BLKF_CLOSET = $10
BLKP_CLOSET = 2
BLKF_DOOR   = $08
BLKP_DOOR   = 2

charmap:  ; room character (the byte .str emits) -> block id
  .byte $00, $00, $00, $01, $00, $0B, $00, $00
  .byte $00, $00, $09, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $02, $00, $00
  .byte $00, $00, $00, $00, $0C, $00, $00, $00
  .byte $00, $00, $00, $00, $08, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $03
  .byte $00, $00, $00, $00, $00, $00, $06, $00
  .byte $00, $00, $00, $04, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $05
  .byte $00, $00, $00, $00, $00, $00, $07, $00
  .byte $00, $00, $00, $00, $0A, $00, $00, $00

CH_SPAWN1 = $11  ; where player 1 starts the room
CH_SPAWN2 = $12  ; where player 2 starts the room

ms_tl:  ; sprite tile in the TL corner of each metasprite
  .byte $00, $00, $00, $08, $0C, $10, $14, $18

ms_tr:  ; sprite tile in the TR corner of each metasprite
  .byte $01, $01, $01, $09, $0D, $11, $15, $19

ms_bl:  ; sprite tile in the BL corner of each metasprite
  .byte $02, $04, $06, $0A, $0E, $12, $16, $1A

ms_br:  ; sprite tile in the BR corner of each metasprite
  .byte $03, $05, $07, $0B, $0F, $13, $17, $1B

