; SPDX-License-Identifier: CC0-1.0
; NOISY NEIGHBORS -- the tune. GENERATED by tools/genmusic.py; edit the notes
; there, not the numbers here.
;
; D harmonic minor, 150 BPM, sixteen bars on a loop. Four voices: the hook on
; pulse 1, a sixteenth-note arpeggio on pulse 2, root-and-octave bass on the
; triangle, and kick, snare and hats on the noise channel.
;
; The song is 256 rows long on purpose. A byte counter wraps at exactly that, so
; looping the tune costs an INX and nothing else.

MUSIC_ROWS  = 256
MUSIC_TEMPO = 6
NOTE_REST   = $FF
NOTE_HOLD   = $FE
DRUM_NONE   = 0
DRUM_KICK   = 1
DRUM_SNARE  = 2
DRUM_HAT    = 3

note_lo:  ; pulse timer, low byte, C2 upwards
  .byte $AD, $4D, $F3, $9D, $4C, $00, $B8, $74
  .byte $34, $F8, $BF, $89, $56, $26, $F9, $CE
  .byte $A6, $80, $5C, $3A, $1A, $FB, $DF, $C4
  .byte $AB, $93, $7C, $67, $52, $3F, $2D, $1C
  .byte $0C, $FD, $EF, $E1, $D5, $C9, $BD, $B3
  .byte $A9, $9F, $96, $8E, $86, $7E, $77, $70
  .byte $6A, $64, $5E, $59, $54, $4F, $4B, $46
  .byte $42, $3F, $3B, $38

note_hi:  ; pulse timer, high three bits
  .byte $06, $06, $05, $05, $05, $05, $04, $04
  .byte $04, $03, $03, $03, $03, $03, $02, $02
  .byte $02, $02, $02, $02, $02, $01, $01, $01
  .byte $01, $01, $01, $01, $01, $01, $01, $01
  .byte $01, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00

tri_lo:  ; triangle timer, low byte
  .byte $56, $26, $F9, $CE, $A6, $80, $5C, $3A
  .byte $1A, $FB, $DF, $C4, $AB, $93, $7C, $67
  .byte $52, $3F, $2D, $1C, $0C, $FD, $EF, $E1
  .byte $D5, $C9, $BD, $B3, $A9, $9F, $96, $8E
  .byte $86, $7E, $77, $70, $6A, $64, $5E, $59
  .byte $54, $4F, $4B, $46, $42, $3F, $3B, $38
  .byte $34, $31, $2F, $2C, $29, $27, $25, $23
  .byte $21, $1F, $1D, $1B

tri_hi:  ; triangle timer, high three bits
  .byte $03, $03, $02, $02, $02, $02, $02, $02
  .byte $02, $01, $01, $01, $01, $01, $01, $01
  .byte $01, $01, $01, $01, $01, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00, $00, $00, $00, $00
  .byte $00, $00, $00, $00

song_lead:  ; pulse 1: the hook
  .byte $26, $FE, $FE, $FE, $29, $FE, $28, $FE
  .byte $26, $FE, $FE, $FE, $21, $FE, $24, $FE
  .byte $26, $FE, $FE, $FE, $2D, $FE, $2B, $FE
  .byte $29, $FE, $28, $FE, $26, $FE, $FE, $FE
  .byte $22, $FE, $FE, $FE, $26, $FE, $29, $FE
  .byte $2E, $FE, $FE, $FE, $2D, $FE, $29, $FE
  .byte $2B, $FE, $FE, $FE, $28, $FE, $24, $FE
  .byte $28, $FE, $2B, $FE, $2D, $FE, $FE, $FE
  .byte $26, $FE, $FE, $FE, $29, $FE, $2D, $FE
  .byte $32, $FE, $FE, $FE, $2D, $FE, $29, $FE
  .byte $28, $FE, $FE, $FE, $2B, $FE, $29, $FE
  .byte $28, $FE, $26, $FE, $25, $FE, $FE, $FE
  .byte $29, $FE, $28, $FE, $26, $FE, $24, $FE
  .byte $21, $FE, $FE, $FE, $26, $FE, $29, $FE
  .byte $28, $FE, $25, $FE, $28, $FE, $2D, $FE
  .byte $29, $FE, $28, $FE, $26, $FE, $FF, $FE
  .byte $26, $FE, $FE, $FE, $29, $FE, $28, $FE
  .byte $26, $FE, $FE, $FE, $21, $FE, $24, $FE
  .byte $26, $FE, $29, $FE, $2D, $FE, $32, $FE
  .byte $30, $FE, $2E, $FE, $2D, $FE, $FE, $FE
  .byte $2E, $FE, $FE, $FE, $2D, $FE, $29, $FE
  .byte $26, $FE, $29, $FE, $2E, $FE, $FE, $FE
  .byte $30, $FE, $FE, $FE, $2E, $FE, $2B, $FE
  .byte $28, $FE, $2B, $FE, $30, $FE, $FE, $FE
  .byte $32, $FE, $FE, $FE, $2D, $FE, $29, $FE
  .byte $26, $FE, $FE, $FE, $29, $FE, $2D, $FE
  .byte $32, $FE, $30, $FE, $2E, $FE, $2D, $FE
  .byte $2B, $FE, $29, $FE, $28, $FE, $FE, $FE
  .byte $29, $FE, $28, $FE, $26, $FE, $25, $FE
  .byte $26, $FE, $28, $FE, $29, $FE, $2B, $FE
  .byte $2D, $FE, $FE, $FE, $28, $FE, $25, $FE
  .byte $21, $FE, $FE, $FE, $FF, $FE, $FE, $FE

song_harm:  ; pulse 2: the arpeggio
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $16, $1A, $1D, $1A, $16, $1A, $1D, $1A
  .byte $16, $1A, $1D, $1A, $16, $1A, $1D, $1A
  .byte $18, $1C, $1F, $1C, $18, $1C, $1F, $1C
  .byte $18, $1C, $1F, $1C, $18, $1C, $1F, $1C
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $11, $15, $18, $15, $11, $15, $18, $15
  .byte $11, $15, $18, $15, $11, $15, $18, $15
  .byte $15, $19, $1C, $19, $15, $19, $1C, $19
  .byte $15, $19, $1C, $19, $15, $19, $1C, $19
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $16, $1A, $1D, $1A, $16, $1A, $1D, $1A
  .byte $16, $1A, $1D, $1A, $16, $1A, $1D, $1A
  .byte $18, $1C, $1F, $1C, $18, $1C, $1F, $1C
  .byte $18, $1C, $1F, $1C, $18, $1C, $1F, $1C
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1D, $21, $1D, $1A, $1D, $21, $1D
  .byte $1A, $1F, $22, $1F, $1A, $1F, $22, $1F
  .byte $1A, $1F, $22, $1F, $1A, $1F, $22, $1F
  .byte $11, $15, $18, $15, $11, $15, $18, $15
  .byte $11, $15, $18, $15, $11, $15, $18, $15
  .byte $15, $19, $1C, $19, $15, $19, $1C, $19
  .byte $15, $19, $1C, $19, $15, $19, $1C, $19

song_bass:  ; triangle: root and octave
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $0A, $FE, $16, $FE, $0A, $FE, $16, $FE
  .byte $0A, $FE, $16, $FE, $0A, $FE, $16, $FE
  .byte $0C, $FE, $18, $FE, $0C, $FE, $18, $FE
  .byte $0C, $FE, $18, $FE, $0C, $FE, $18, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $05, $FE, $11, $FE, $05, $FE, $11, $FE
  .byte $05, $FE, $11, $FE, $05, $FE, $11, $FE
  .byte $09, $FE, $15, $FE, $09, $FE, $15, $FE
  .byte $09, $FE, $15, $FE, $09, $FE, $15, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $0A, $FE, $16, $FE, $0A, $FE, $16, $FE
  .byte $0A, $FE, $16, $FE, $0A, $FE, $16, $FE
  .byte $0C, $FE, $18, $FE, $0C, $FE, $18, $FE
  .byte $0C, $FE, $18, $FE, $0C, $FE, $18, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $02, $FE, $0E, $FE, $02, $FE, $0E, $FE
  .byte $07, $FE, $13, $FE, $07, $FE, $13, $FE
  .byte $07, $FE, $13, $FE, $07, $FE, $13, $FE
  .byte $05, $FE, $11, $FE, $05, $FE, $11, $FE
  .byte $05, $FE, $11, $FE, $05, $FE, $11, $FE
  .byte $09, $FE, $15, $FE, $09, $FE, $15, $FE
  .byte $09, $FE, $15, $FE, $09, $FE, $15, $FE

song_drum:  ; noise: kick, snare, hats
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $02, $02, $02, $02, $02, $00, $02, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $01, $00, $03, $00, $02, $00, $03, $00
  .byte $02, $02, $02, $02, $02, $00, $02, $00

